### ISSUE TITLE
I need to implement the drop down feature for one of the fields in the CRUD Table

### ISSUE THREAD

**Issue by snsarma** [xvicmanx/react-crud-table#1]
Hi

React-Crud Table has been very helpful in our implementation, But I had a query once we create a new record all of them in the form turn out to be text fields , how do I change them to a drop down ? Could you please provide your inputs? Thanks , Your help is much appreciated.

Regards
Shravya

**Comment by xvicmanx** [comment]
You could create a renderer component like:

```
const DropdownRenderer = ({ field }) => (
  <select
    name={field.name}
    value={field.value}
    onChange={field.onChange}
  >
    <option value="first">First</option>
    <option value="second">Second</option>
    <option value="third">Third</option>
    <option value="fourth">Fourth</option>
  </select>
);
```

And then pass it to the field like:

```
<Field
          name="order"
          label="Order"
          render={DropdownRenderer}
        />

```

**Comment by LorhanSohaky** [comment]
Is `render` not working?

**Comment by xvicmanx** [comment]
@LorhanSohaky Are you getting an error? Or is not rendering?

**Comment by LorhanSohaky** [comment]
It is not calling the function that I pass in the render
