### ISSUE TITLE
Don't work "type"

### ISSUE THREAD

**Issue by pawel54321** [xvicmanx/react-crud-table#2]
Hi,
I add type example:
`<Field type="number" name="a" label="A" placeholder="10"/>`
Never don't work "type" Why?
" #### type: string The type of the field. This can be (text, number, date, etc). It is useful when you want to make it queryable and/or sortable ".

**Comment by xvicmanx** [comment]
Fixed on https://github.com/xvicmanx/react-crud-table/commit/5c3dea2744e015db1fd902660e21ab28f436412f
