### ISSUE TITLE
How to make the fields in the react crud table readonly ?

### ISSUE THREAD

**Issue by snsarma** [xvicmanx/react-crud-table#4]
Hi

The react crud table has fields for id description and so forth.
These fields when create , update or delete tasks are done a form is popped up.
Each of the fields are editable, Is there a way to make them read-only there is a read-only attribute for form controls , is there a way out for fields to be made read-only?
Your inputs are required.
Thanks.

Regards
Shravya

**Comment by xvicmanx** [comment]
Fixed on https://github.com/xvicmanx/react-crud-table/commit/5c3dea2744e015db1fd902660e21ab28f436412f
