### ISSUE TITLE
Data is coming dynamically but not displaying on the table

### ISSUE THREAD

**Issue by NagaveniLinkEZ** [xvicmanx/react-crud-table#5]
For me Data is coming dynamically but not displaying on the table.

Hard code data is showing for me also how you did it in codeSanbox.
but when data is coming from server not displaying, data is exactly same as hardcoded json.

**Comment by NagaveniLinkEZ** [comment]
> For me Data is coming dynamically but not displaying on the table.
> 
> Hard code data is showing for me also how you did it in codeSanbox.
> but when data is coming from server not displaying, data is exactly same as hardcoded json.

**Comment by xvicmanx** [comment]
Fixed on https://github.com/xvicmanx/react-crud-table/commit/d165a37d531bad7dac99d8b80c0d70d260e6c34d
